/*
 The sequence of triangle numbers is generated by adding the natural numbers.
 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 List the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28

 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 * */

var getFirstTriangleNumberWithDivisorOver = (function () {
    function getFirstTriangleNumberWithDivisorOver(count) {
        var i = 1;
        var triangleNumber = 1;
        while (countDivisors(triangleNumber) <= count) {
            i++;
            triangleNumber += i;
        }

        return triangleNumber;
    }

    function countDivisors(number) {
        var divisorsNumber = 0;
        var end = Math.floor(Math.sqrt(number));
        for (var i = 1; i <= end; i++) {
            if (number % i == 0) {
                divisorsNumber++;
                if (i * i != number)
                    divisorsNumber++;
            }
        }
        return divisorsNumber;
    }

    return getFirstTriangleNumberWithDivisorOver;
})();



